name: css-fall2023-class7
channels:
  - pip
  - conda-forge
dependencies:
  - python=3.8
  - spacy=3.6.1
  - nltk=3.8.1
  - notebook=6.5.6
  - pandas=2.0.3
  - gensim=3.8.3
  - scikit-learn=1.3.1
  - vaderSentiment=3.3.2
  - sentida=0.6.0
  - danlp=0.1.2
